name: dlc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.25
  - scipy
  - pandas>=2.0
  - matplotlib
  - scikit-learn
  - scikit-image
  - statsmodels
  - opencv
  - pillow
  - shapely
  - albumentations
  - imgaug
  - deeplabcut
  - napari
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - tqdm
  - joblib
  - pyyaml
  - requests
  - protobuf
  - pip
  - plotly>=5.20
  - pyqt>=5.15
  - pyqtwebengine
  - kaleido>=0.2
  - pip:
      - wandb
